name: Deploy Full Stack

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |

            echo "=== BACKEND ==="
            cd ~/api-escalada
            git pull origin main

            docker stop api-escalada || true
            docker rm api-escalada || true

            docker build -t api-escalada .
            docker run -d --name api-escalada -p 8080:8080 api-escalada

            echo "=== FRONTEND ==="
            cd ~/app-escalada
            git pull origin main

            npm install
            npm run build

            sudo rm -rf /var/www/escalada/*
            sudo cp -r dist/* /var/www/escalada/
