name: Deploy Backend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Backend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/api-escalada
            git pull origin main

            docker stop api-escalada || true
            docker rm api-escalada || true

            docker build -t api-escalada .
            docker run -d --name api-escalada -p 8080:8080 api-escalada
